import Head from 'next/head'
import { useRouter } from 'next/router'
import { ListTasks } from 'src/components/tasks'

export default function home(props) {
  const router = useRouter()

  const createNewTask = () => router.push('/task/new')

  return (
    <>
      <div className='container'>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main>
          <section>
            <div className='cont-addTask'>
              <button onClick={createNewTask}>Crear tarea</button>
            </div>
          </section>
          <ListTasks tasks={props.tasks} />
        </main>
      </div>
      <style jsx>{`
        .container {
          height: 100%;
          display: flex;
          flex-direction: column;
          justify-content: flex-start;
          align-items: center;
        }
        main {
          width: 100%;
          height: 100%;
          padding: 0.5rem;
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(17rem, 1fr));
          justify-content: center;
          align-items: center;
        }
        section {
          width: 100%;
          height: 100%;
          min-height: 10rem;
          max-height: 17rem;
          display: flex;
          justify-content: center;
          align-items: center;
          padding: 0.5rem;
        }
        .cont-addTask {
          width: 100%;
          height: 100%;
          background: #eee;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          border: 1px solid #fff;
          border-radius: 0.5rem;
        }
        button {
          background: #2575d0;
          color: #fff;
          border: none;
          border-radius: 0.5rem;
          padding: 1rem;
          font-size: 1.5rem;
        }
      `}</style>
    </>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/task')
  const data = await res.json()

  return {
    props: {
      tasks: data,
    },
  }
}
