import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function home(props) {
  console.log(props)
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          {props.tasks.length === 0 ? (
            <h2>No hay tareas</h2>
          ) : (
            <>
              {props.tasks.map((task) => (
                <div key={task.id}>
                  <h3>{task.title}</h3>
                  <p>{task.description}</p>
                </div>
              ))}
            </>
          )}
        </main>
      </div>
      <style jsx>{`
        .container {
          min-height: 100vh;
          padding: 0 0.5rem;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }
        main {
          background: #222;
          /* padding: 5rem 0; */
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }
      `}</style>
    </>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/task')
  const data = await res.json()

  // console.log(data);

  return {
    props: {
      tasks: data,
    },
  }
}
